version: "2"

services:
  nginx:
    build: nginx
    ports:
      - 8080:80
    volumes_from:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx

  php:
    build:
      context: php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/app/logs
